[package]
name = "gitflex"
version = "0.1.1"
edition = "2024"
description = "A git wrapper TUI that cleans up old branches and makes it easier to switch, rebase, and merge in a repo with many branches"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Wattsy2020/gitflex"

[dependencies]
clap = { version = "4", features = ["derive"] }
git2 = { version = "0.21", default-features = false }
ratatui = "0.30"
regex = "1"
sqlx = { version = "0.9", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
] }
terminal-light = "1.9"
thiserror = "2"
tokio = { version = "1", features = ["rt"] }
tui-input = "0.15"

[dev-dependencies]
tempfile = "3"
